### PR TITLE
gtkui: New plugin preferences UI

### PR DESCRIPTION
**Pull request by saivert**
Notes:

I had to change the code in `apply_conf` from using `lookup_widget` glade utility function to `g_object_get_data` directly as it needs to work with any container and not just top levels where it can find the outermost parent. `gtkui_run_dialog` expected a parent dialog passed to it which remains until none of the child objects are needed. I hope this change has no side effects this time.

### CODE REVIEW

**Comment by kuba160** [comment]
Look on Windows (GTK2):
image
GTK3:
image

Previous look for reference:
image

**Comment by saivert** [comment]
Not sure what to do about the inset border on GTK2 really. It looks okay here with Adwaita GTK2 theme on Gnome desktop. Styling and themes is pain.
Screenshot from 2021-02-26 08-21-50

**Comment by saivert** [comment]
@kuba160 so I made some fixes to the styling. Should look better on GTK2 now. The buttons also look more appropriate on GTK3 now.

**Comment by Alexey-Yakovenko** [comment]
Looks great! I still didn't have time to verify or look at the code, but looking forward to it :D

**Comment by Alexey-Yakovenko** [comment]
So, it actually works quite great, but I see 2 issues.. although I'm not sure what's the best way to fix it and whether it makes sense.

1. Some widgets have too large min width, so they cause horizontal scrolling.. probably the min-width should be reduced. I can't see where it's set though, maybe it's added by default by Gtk to GtkEntry, or something like this.
2. The scrollbars act super weird -- although this is probably something that only happens with Mac version of GTK, and maybe is irrelevant. I don't care as long as it works well on Linux. Here's what's happening:
    * Initially, I can only use the Vertical scrollbar, and it's invisible.. Only becomes visible when I start scrolling
    * I can't use horizontal scrollbar with the mouse wheel - holding any modifier keys (shift/cmd/opt/ctrl) doesn't help.
    * I can scroll horizontally by moving the mouse towards the bottom edge of the view, then the horizontal scrollbar appears, and I can drag, but:
    * After I drag the horizontal one -- I can no longer scroll the vertical one.
    * Also, if the mouse pointer is over any dropdown control, using the mouse wheel will change the value of the dropdown, instead of scrolling the view.

**Comment by Alexey-Yakovenko** [comment]
Either way, I think it's usable as it is, so if you're ready -- I can hit the merge button.

**Pull request merged**
