### PR TITLE
psf module small fixes

### PR DESCRIPTION
**Pull request by Greedysky**

### CODE REVIEW

**Comment by Alexey-Yakovenko** [comment]
Could you please describe what's getting fixed?

**Comment by Greedysky** [comment]
The minissf file can not be imported, even if the ssflib file already exists

**Comment by Greedysky** [comment]
[test_file.zip](https://github.com/DeaDBeeF-Player/deadbeef/files/5947848/test_file.zip)

**Comment by Alexey-Yakovenko** [comment]
Thank you

**Pull request merged**
