### PR TITLE
streamer: stop after current now works like fb2k (#2124)

### LINKED ISSUE #2124: Переход выделения на следующий трек при включенной опции "Stop after current"
Есть ли аналог опции "Cursor follows playback" (из проигрывателя Foobar)?
При включенной опции "Stop after current" хотелось бы, чтобы по окончании трека (и остановки воспроизведения) выделение переходило на следующий трек. И по нажатии на кнопку Play (клавишу Enter) - начинал звучать следующий трек.

Deadbeef version: 1.8.0
OS: Debian

### PR DESCRIPTION
**Pull request by rsekman**
after the streamer stops due to stop after current (track/album), hitting play will now play the next track. before it would play the track that just ended

Resolves #2124

Unfortunately, the selection indicated in `gtkui` is not updated to reflect the new cursor position. I think this may require new signals to implement.

### CODE REVIEW

**Comment by Alexey-Yakovenko** [comment]
You can change the selection by running something like this
```
plt_deselect_all(plt);
plt_item_set_selected(plt, next, 1);
sendmessage (DB_EV_PLAYLISTCHANGED, 0, DDB_PLAYLIST_CHANGE_SELECTION, 0);
```
There's no need to propagate this as an event.

**Comment by rsekman** [comment]
> You can change the selection by running something like this

Oh, excellent. I'm not familiar enough with the codebase yet so i was trying with `DB_EV_SONGCHANGED`.
There is a bit of a timing issue with this: the selection will be advanced when the last streaming block is loaded, not when it finishes playing. As a result the selection marker advances just before the playing track indicator. A video may be easier to understand:

https://user-images.githubusercontent.com/29686694/154492250-dd6939e3-282c-44c3-b932-76d8b4a5faf3.mp4

The next track, Run To The Hills, becomes highlighted before The Number of the Beast stops being bold. Of course this is only an issue if one happens to be looking at the playlist just as the track ends...

> I believe, this behavior is configurable in fb2k, but not in deadbeef.

I don't think it is. But it has been almost a year since I last used fb2k. fb2k has both "cursor follows playback" and "playback follows cursor" and I was never quite able to figure out the.

**Comment by Alexey-Yakovenko** [comment]
> There is a bit of a timing issue with this: the selection will be advanced when the last streaming block is loaded, not when it finishes playing. As a result the selection marker advances just before the playing track indicator.

If you want to have this in sync - it will be quite hard.
You would have to put some sort of a special marker into the last streaming block, and ensure that the marker is carried to the decoded blocks queue.
And then when this decoded block is consumed -- you would know that the cursor and selection needs to jump to the next track.

Maybe you should give it a try.

**Comment by rsekman** [comment]
> Maybe you should give it a try.

I might when I don't have anything with a higher reward/effort ratio to work on. For now I am not bothered enough by it. It is more important to me that "play" behaves as I expect it to. Most of the time I am not looking at the playlist, after all.

**Comment by Oleksiy-Yakovenko** [comment]
Closing: out of date

**Pull request closed without merging**
