### PR TITLE
Update ko.po

### PR DESCRIPTION
**Pull request by MarongHappy**

### CODE REVIEW

**Comment by MarongHappy** [comment]
I finished translating Korean.

**Comment by Alexey-Yakovenko** [comment]
Hello, I can't see any untranslated Korean strings in Transifex.
https://www.transifex.com/deadbeef-player/deadbeef-player/translate/#ko/deadbeef/15504136
What does your translation change?

**Comment by MarongHappy** [comment]
Hello.
It has been a long time since the Korean translation was completed, but
Korean was not being applied when installing the program.
That's why I wrote a thread.
We have been translating DeaDbeeF's Korean since 2019.

2021년 6월 15일 (화) 오후 7:21, Alexey Yakovenko ***@***.***>님이 작성:

**Comment by Alexey-Yakovenko** [comment]
Thanks for your contribution. Please consider using Transifex instead of submitting po file, as this is creating much manual work for me.

**Comment by MarongHappy** [comment]
I always used Transifex to translate Korean, but there was a problem using
Korean when installing the program.
Thank you for your interest in my efforts in Korean translation.
Sorry for creating a lot of manual po file job creation.

2021년 6월 18일 (금) 오전 5:32, Alexey Yakovenko ***@***.***>님이 작성:

**Pull request merged**
