### PR TITLE
Correct signed-unsigned char conversion.

### PR DESCRIPTION
**Pull request by Vascom**
This correction need to build deadbeef on ARM and PPC systems.

### CODE REVIEW

**Comment by Vascom** [comment]
Can you do it as you see it?

**Comment by Alexey-Yakovenko** [comment]
I thought it would be easy enough for you to do it, since you're already on it. But ok.

**Comment by Alexey-Yakovenko** [comment]
Have you tested that s3m and sid formats still work correctly after your change?
This code actually compiles and works fine for ARM (tested on android), but looking closely at your change, it seems like it will get wrong values at runtime.

**Comment by Vascom** [comment]
I am not tested it.
You can look at compile errors here http://koji.rpmfusion.org/kojifiles/work/tasks/4507/224507/build.log
and here http://koji.rpmfusion.org/kojifiles/work/tasks/4514/224514/build.log
It is for armv7hl but same errors for aarch64, ppc64 and ppc64le.

**Comment by Alexey-Yakovenko** [comment]
```
#include <stdio.h>
#include <stdint.h>

int main () {
    int8_t signedValue = '\x80'; // <-- the original code
    int castFromSigned = signedValue;
    printf ("%d\n", castFromSigned); // <-- prints "-128"

    uint8_t unsignedValue = '\x80'; // <-- your modification (char is unsigned on ARM)
    int castFromUnsigned = unsignedValue;
    printf ("%d\n", castFromUnsigned); // <-- prints "128"
}```

**Comment by Vascom** [comment]
OK. So I suggest you corect code. You better know this :)

**Comment by Alexey-Yakovenko** [comment]
Ok so the errors you're getting is because of your compiler settings.

There are two problems with your pull request:

1. the code would not work correctly on ARM after you change
2. you would start getting the same compile warnings on x86 architectures

I'd happily fix the problem, but I don't have a possibility to test that the modified code works correctly on ARM atm.

**Comment by Vascom** [comment]
What compiler settings causes this errors?

**Comment by Alexey-Yakovenko** [comment]
`-Wnarrowing` is the one.

**Comment by Vascom** [comment]
As I understand it from `-Wall` compiler directive. And I am don't think that after removing it an compile without errors program will work correctly. So it is better correct code and don't touch compiler.

**Comment by Alexey-Yakovenko** [comment]
I'm not suggesting touching the compiler. I'm saying that this program code is valid and works, but obviously you can break it by using -Wall and treat warnings as errors.

It can be fixed, but it would need extensive testing before I can merge that. The fix would not be as simple as it looks.

**Comment by Vascom** [comment]
May be make explicit type conversion `like static_cast<signed char>('\x80')`?
This should not break down the work.

**Comment by Alexey-Yakovenko** [comment]
commits 394536bd135dd5f9fac211c391ce2e1a04bda6da and 8fdeb8102d7a8be6773dc4accc5fe87901488724 should fix your problems

**Comment by Vascom** [comment]
Thanks.
Also need add #include <cstdint> to s3m.h.

**Comment by Alexey-Yakovenko** [comment]
Are you getting a compile error without adding this include?
Cause it builds fine here on both macOS and Linux.

**Comment by Alexey-Yakovenko** [comment]
Ah.. that's before I already fixed that with another commit 7163099d55c64bf11c3dac4dadfd83a0495ea207

**Comment by Vascom** [comment]
OK

**Pull request closed without merging**
