### PR TITLE
Bugfix for #2231

### PR DESCRIPTION
**Pull request by kpcee**
Here is a possible bugfix for #2231 that restores the old behavior for Gtk3. With my older local copy it works fine. However, the current Git version has a problem and cannot remember the correct position of the window if you click on the tray icon several times. This is not due to my submitted patch because this behavior can be observed even before when you revert to a previous state. There must have been a change that caused this, because it still works in 1.82.

### CODE REVIEW

**Comment by Alexey-Yakovenko** [comment]
It's quite possible, that the other problem was caused by the change that added "start hidden" option.

**Comment by kpcee** [comment]
Are you able to reproduce the problem? I have now tried until I found the commit that triggers the problem. For me the problem starts with the commit:

> commit bbff7bbb80e041fadd91624f1ae11b97ddbbbc1c (HEAD -> Bugfix)
> Date:   Mon Jun 3 18:07:07 2019 +0000
> gtkui: restore window position relative to the monitor DeaDBeeF is currently on

**Comment by Alexey-Yakovenko** [comment]
@saivert any comments to this? would it be possible to re-verify your change and fix it?
It's quite risky to accumulate changes in the same area, when it's impossible to verify their correctness due to tech debt.

**Comment by Alexey-Yakovenko** [comment]
@kpcee sorry, I only started looking at a few PRs and bugs yesterday. Only got to reading the comments / summaries, haven't tried reproducing.

**Comment by Alexey-Yakovenko** [comment]
@kpcee seems like the author of the original change is not available, and I will have to revert his commit.
It doesn't seem important to me to have multimonitor support for windows position saving, when singlemonitor is not working. But I will first need to test this anyway.

**Comment by saivert** [comment]
Quite possible because I'm not zeroing out the struct for the monitor rect in that patch.
In https://github.com/DeaDBeeF-Player/deadbeef/commit/bbff7bbb80e041fadd91624f1ae11b97ddbbbc1c#diff-553100c0eadbbed1e24f24dcc5e1cf1dR49

**Comment by Alexey-Yakovenko** [comment]
@saivert this change solves the problem indeed. great spot! thanks a lot. I'm adding the fix.

**Comment by Alexey-Yakovenko** [comment]
@kpcee your fix works fine too! great job, merging.

**Pull request merged**
