### PR TITLE
Ignore duplicate items

### PR DESCRIPTION
**Pull request by kpcee**
This patch adds a new entry "Ignore Duplicates" to the playlist context menu. It prevents that the user can add files twice, the setting have to set for each playlist separately. Possible partial solution for feature request #504. 

Bugfix: Changes to the "Enable Autosort" setting were not always saved, because a plt_modified (plt); was missing.

### CODE REVIEW

**Comment by Alexey-Yakovenko** [comment]
The playlist context menu is a wrong place for this option.
It needs to be in the settings, or perhaps in the file menu, but not in the context menu.

**Comment by Alexey-Yakovenko** [comment]
Although, if it's a playlist-specific option, this might be viable, but I'm still not sure it's a good idea. It's possibly even better to add a checkbox to the file dialog.

**Comment by kpcee** [comment]
I like it the way it is now, but of course it's not my decision. If it is, I would add it in the settings and it would apply to all playlists. To round things up, we could add a "Remove Duplicate Items" in the Edit menu, in addition to the PR #2299.

**Comment by Alexey-Yakovenko** [comment]
There are a few things that needed to be discussed before starting to work on the feature.
It is also written in the [contributing guide](https://github.com/DeaDBeeF-Player/deadbeef/blob/master/CONTRIBUTING.md).

Not discussing design leads to big code changes, because redesign will be needed.

For me, it's pointless to review the code implementing the feature, since it isn't backed by any design.

* I disagree that the option needs to be named "Ignore duplicates" -- it's not what the feature is doing
* I disagree that it's put in the playlist tab context menu -- it needs to be discussed and decided where is the best place
* I disagree with making this option a global variable. It needs to be some sort of a parameter, maybe a flag, to the function which adds the files. It needs to be testable in some way, and it needs to be configurable without going through the config & the global variable.

**Comment by kpcee** [comment]
> For me, it's pointless to review the code implementing the feature, since it isn't backed by any design.

I think the design fits perfectly, as it fits perfectly with the Autosort feature. If you would move "Ignore Duplicates" to the main menu, you would distribute related functions across the user interface.

> * I disagree that the option needs to be named "Ignore duplicates" -- it's not what the feature is doing

This feature prevents a file from being added to the playlist twice, whether this is called "(Ignore|Do Not Add|Filter Out|Disallow) Dublicates" or similar is a matter of taste.

I don't want to argue, especially over something like this. Since the feature was requested several times, I took a look at it. No more, no less.

**Comment by Alexey-Yakovenko** [comment]
This attitude is not going to help anything.
I don't mind other people working on features, but this work requires some coordination and discussion before jumping to code.

I need to consider more things -- like how easy it is to discover and use, what problems it may cause in the future, how to reuse code and how to fit the design on other platforms, and so on.

**Pull request closed without merging**
