### PR TITLE
Fix signed char errors on ARM/PPC, fix GCC 7 warnings

### PR DESCRIPTION
**Pull request by StefanBruens**

### CODE REVIEW

**Comment by Alexey-Yakovenko** [comment]
I'm not taking PRs with patches to 3rd party deps unless they fix actual problems.
GCC warnings are not.

**Comment by Alexey-Yakovenko** [comment]
This PR may be accepted if the changes get accepted upstream, and you post commit links.

**Comment by StefanBruens** [comment]
You obviously are unable to understand architectural differences, and do not understand what "undefined behaviour" in the C standard means. Irresponsible persons like you should not claim maintainership of any software.

**Comment by Alexey-Yakovenko** [comment]
@StefanBruens 

I think you're misunderstanding something. The libraries which you patched are 3rd party -- I'm not maintaining them. You need to post the patches upstream first.

I'm not accepting such patches mainly because they make it hard to merge updates from upstream.

I did not write the code you changed, and there's even no guarantee it's used in this project.

**Comment by Alexey-Yakovenko** [comment]
And btw, I can assure you that adplug and libsidplay2 both work fine when built for ARM on android. And they worked fine on PPC too when I last checked, but that was many years ago.

**Pull request closed without merging**
