### PR TITLE
tf: Allow arbitrary strings in %tracknumber% and %track number%

### LINKED ISSUE #2062: Allow %tracknumber% with non-digit characters
I have a vinyl rip with two tracks on each side. The track numbers in FLAC metadata are prefixed with a side letter: A01, A02, B01, and B02.

While foobar2000 allows such "numbers" for %tracknumber%, DeaDBeeF gives an empty string in such cases: https://github.com/DeaDBeeF-Player/deadbeef/blob/3b8b2fae56e43749cf46c42463e282548a73c315/tf.c#L1959-L1962

This obviously gives issues when converting files with default "%tracknumber% - %title%" format. In my particular case, two tracks on the rip are named "Untitled", so when I try to convert FLACs to MP3s, two files have the same name (" - Untitled.mp3"), and depending on settings, the second track is either skipped or will overwrite the first one.

### PR DESCRIPTION
**Pull request by danpla**
Fixes #2062.

### CODE REVIEW

**Comment by Alexey-Yakovenko** [comment]
This change breaks the existing functionality, see the [build log](https://api.travis-ci.org/v3/job/504811022/log.txt) for details.

**Comment by Alexey-Yakovenko** [comment]
A simpler and more reliable approach would be to check if the first character in `track` field is not a digit, and in this case leave the text alone without any transformation.

**Comment by danpla** [comment]
Digits may be followed by non-digit characters, in which case `atoi()` will silently drop them.

I'll fix the failures soon.

**Comment by Alexey-Yakovenko** [comment]
I applied a simpler fix, added tests, and validated the behavior.

**Pull request closed without merging**
