### PR TITLE
Masively update for translation.

### PR DESCRIPTION
**Pull request by laichiaheng**
It corrects lots of mismatch translations.

### CODE REVIEW

**Comment by Alexey-Yakovenko** [comment]
Is it possible to submit this to transifex?

**Comment by laichiaheng** [comment]
It has, but it is still wrong here.

**Comment by Alexey-Yakovenko** [comment]
ok, then I just need to pull from transifex. I will do that instead.

**Comment by Alexey-Yakovenko** [comment]
pulled.

**Comment by laichiaheng** [comment]
@Alexey-Yakovenko They are still not pulled in master branch.

**Comment by Alexey-Yakovenko** [comment]
Sorry, I forgot to push to github. Are they up now?

**Comment by laichiaheng** [comment]
@Alexey-Yakovenko Yes, thanks.
By the way, I didn't see the "Minimize to tray when startup" in Transifex.

**Comment by Alexey-Yakovenko** [comment]
It was just added via a pull request from a contributor

**Comment by Alexey-Yakovenko** [comment]
(I will probably change this text before pushing to transifex)

**Comment by laichiaheng** [comment]
@Alexey-Yakovenko I'm deeply sorry, I saw some deadly wrong translation that I didn't notice. Could you pull it again? Thanks.

**Comment by Alexey-Yakovenko** [comment]
done

**Pull request closed without merging**
