### PR TITLE
Update sv.po

### PR DESCRIPTION
**Pull request by jony0008**
Please update sv.po

### CODE REVIEW

**Comment by Alexey-Yakovenko** [comment]
I will try, but I'm not sure I will be able to do that without causing problems. Please see this: 

https://github.com/DeaDBeeF-Player/deadbeef/wiki/FAQ#i-want-to-help-with-translation-how-do-i-do-that

**Comment by jony0008** [comment]
@Alexey-Yakovenko I would have translated it on Transifex if I would have known. There were no information on the contributing page: https://github.com/DeaDBeeF-Player/deadbeef/blob/master/CONTRIBUTING.md

**Comment by jony0008** [comment]
@Alexey-Yakovenko I can upload it to Transifex?

**Comment by Alexey-Yakovenko** [comment]
You don't need to get this merged anymore? I didn't yet get to this...

**Comment by jony0008** [comment]
I uploaded it to Transifex, you can merge it from there

**Comment by Alexey-Yakovenko** [comment]
ok, thanks. I'll pull from there as soon as possible.

**Pull request closed without merging**
