### PR TITLE
gtkui: extend gui syntax with a label item

### PR DESCRIPTION
**Pull request by saivert**
Allows you to break up options groups or place a label above an entry box to save on space.

Syntax:

   label "\<label text\>" \<left|center|right\>

### CODE REVIEW

**Comment by Alexey-Yakovenko** [comment]
The syntax looks off to me. Until now, the syntax was always starting with a "property":
`property text type identifier parameters;`

Please change the syntax to match everything else.

**Comment by Alexey-Yakovenko** [comment]
I'm not saying that the original syntax is very good, considering that nobody even tried to think how to make it good -- but it's better to have ugly and consistent, than ugly and random.

**Comment by Alexey-Yakovenko** [comment]
The diff looks surprisingly large for such a small change. Is there a reason for that?

**Comment by Alexey-Yakovenko** [comment]
Because the change touches so much code, I'd not be able to merge this until I'm able to test as much as possible for regressions. There are quite a few dialogs in the player that rely on this functionality, and I don't want them to break apart.

**Comment by Alexey-Yakovenko** [comment]
(and currently I'm stuck without a linux VM, so it'll have to wait for a bit)

**Comment by saivert** [comment]
It indents a lot of existing code to put it inside an if clause.

I can of course change it to always start with property even if it isn't really defining a property. It would simplify the code some.

**Pull request closed without merging**
